spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: MathApp
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cors:
    allowed:
      origin: ${PLATFORM_URL}:${FRONTEND_PORT}
  security:
    secret-key: ${JWT_SECRET_KEY}
  aws:
    s3:
      bucket: ${BUCKET_NAME:mathapp-bucket}
      endpoint: http://${PLATFORM_URL:localhost}:${LOCALSTACK_PORT:4566}
      region: ${BUCKET_REGION:eu-central-1}
  ollama:
    base-url: http://${PLATFORM_URL:localhost}:${OLLAMA_PORT:11434}
    model: gpt-oss:20b

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.springframework.boot.autoconfigure: ERROR