spring:
  datasource:
    url: jdbc:postgresql://${PLATFORM_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  aws:
    s3:
      endpoint: http://localhost:${BUCKET_PORT:9000}
  ollama:
    base-url: http://${PLATFORM_URL:localhost}:${OLLAMA_PORT:11434}
  scheduler:
    daily-exercise-cron: "0 */1 * * * *"