spring:
  datasource:
    url: jdbc:postgresql://postgresql_database:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  aws:
    s3:
      endpoint: http://minio:${BUCKET_PORT:9000}
  ollama:
    base-url: http://ollama:${OLLAMA_PORT:11434}
  scheduler:
    daily-exercise-cron: "0 0 9 * * *"