spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  banner:
    location: 'classpath:mathapp-banner.txt'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: MathApp
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cors:
    allowed:
      origin: ${PLATFORM_URL}:${FRONTEND_PORT}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 3600000 # 1 hour in milliseconds
  aws:
    s3:
      bucket: ${BUCKET_NAME:mathapp-bucket}
      endpoint: http://minio:${LOCALSTACK_PORT:9000}
      region: ${BUCKET_REGION:eu-central-1}
  ollama:
    base-url: http://${PLATFORM_URL:localhost}:${OLLAMA_PORT:11434}
    model: gpt-oss:20b
  frontend:
    url: http://${PLATFORM_URL:localhost}:${FRONTEND_PORT:3000}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
    org.springframework.boot.autoconfigure: ERROR